export const styles = {
  container: {
    flex: 1,
    backgroundColor: '#e4f5f0',
    justifyContent: 'center',
    width: '100%',
  },
  button1: {
    backgroundColor: '#026670',
    alignItems: 'center',
    borderRadius: 7,
    paddingTop: 6,
    paddingBottom: 6,
    marginLeft: 2,
    marginRight: 2,
  },
  button2: {
    backgroundColor: '#026670',
    alignItems: 'center',
    borderRadius: 7,
    paddingTop: 6,
    paddingBottom: 6,
    marginLeft: 2,
    marginRight: 2,
    marginTop: 2,
  },
  button3: {
    backgroundColor: '#026670',
    alignItems: 'center',
    borderRadius: 7,
    paddingTop: 6,
    paddingBottom: 6,
    marginLeft: 2,
    marginRight: 2,
    marginTop: 2,
  },
  button4: {
    backgroundColor: '#D10000',
    alignItems: 'center',
    borderRadius: 7,
    paddingTop: 6,
    paddingBottom: 6,
    marginLeft: 2,
    marginRight: 2,
    marginTop: 20,
  },
  buttonText: {
    color: 'white',
    fontSize: 26,
  },

  inputBox: {
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    padding: 4,
    backgroundColor: '#fff',
    fontSize: 14,
    color: '#026670',
    height: 40,
  },
  inputHeading: {
    fontSize: 20,
    marginTop: 10,
    paddingLeft: 10,
    color: '#026670',
    backgroundColor: '#FEF9C7',
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
  },
  image: {
    alignItems: 'center',
    paddingTop: 50,
    paddingBottom: 40,
    paddingRight: 10,
  },
};
