export const styles = {
  button: {
    backgroundColor: '#026670',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 7,
    padding: 6,
    paddingLeft: 20,
    paddingRight: 20,
    margin: 5,
  },
  buttonText: {
    color: 'white',
    fontSize: 26,
  },
  userAvatar: {
    height: 100,
    width: 100,
    paddingLeft: 100,
    alignItems: 'center',
  },
  title_view: {
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    backgroundColor: '#FEF9C7',
    paddingLeft: 10,
    width: '75%',
    justifyContent: 'center',
  },
  title_text: {
    fontSize: 16,
    color: '#026670',
  },
  view: {
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    backgroundColor: 'white',
    paddingLeft: 10,
    width: '75%',
    justifyContent: 'center',
  },
  text: {
    fontSize: 16,
    color: '#026670',
  },
};
