export const styles = {
  helperPicker: {
    backgroundColor: '#ffffff',
    height: 30,
  },
  imageContainer: {
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
    height: 275,
  },
  image: {
    height: 200,
    width: 200,
  },
  button: {
    backgroundColor: '#026670',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 7,
    padding: 6,
    paddingLeft: 20,
    paddingRight: 20,
    margin: 5,
  },
  buttonText: {
    color: 'white',
    fontSize: 26,
  },
  rowC8_view: {
    width: '50%',
    padding: 2,
  },
  rowC9_view: {
    width: '50%',
    padding: 2,
  },
  commentsButton_view: {
    backgroundColor: '#026670',
    borderRadius: 7,
    padding: 6,
    paddingLeft: 6,
    paddingRight: 6,
    width: '100%',
    alignItems: 'center',
  },
  commentsButton_text: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  helperButton_view: {
    backgroundColor: '#D10000',
    borderRadius: 7,
    padding: 6,
    paddingLeft: 6,
    paddingRight: 6,
    width: '100%',
    alignItems: 'center',
  },
  helperButton_text: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  uploadButton_view: {
    backgroundColor: '#D10000',
    borderRadius: 7,
    padding: 6,
    paddingLeft: 6,
    paddingRight: 6,
    width: '100%',
    alignItems: 'center',
  },
  uploadButton_text: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  changeButton_view: {
    backgroundColor: '#026670',
    borderRadius: 7,
    padding: 6,
    paddingLeft: 6,
    paddingRight: 6,
    width: '100%',
    alignItems: 'center',
  },
  changeButton_text: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  rowContainerR1_view: {
    flexDirection: 'row',
    height: 45,
    marginTop: 3,
  },
  rowContainerR2_view: {
    flexDirection: 'row',
    height: 29,
    marginTop: 3,
  },
  rowContainerR3_view: {
    flexDirection: 'row',
    height: 29,
    marginTop: 5,
  },

  rowC1_view: {
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    backgroundColor: '#FEF9C7',
    paddingLeft: 10,
    width: '27%',
    height: '100%',
    justifyContent: 'center',
  },
  rowC1_text: {
    fontSize: 20,
    color: '#026670',
  },
  rowC2_view: {
    paddingLeft: 5,
    backgroundColor: '#fff',
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    width: '15%',
    height: '100%',
    justifyContent: 'center',
  },
  rowC2_text: {
    fontSize: 14,
    color: '#026670',
  },
  rowC3_view: {
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    backgroundColor: '#FEF9C7',
    paddingLeft: 10,
    width: '15%',
    height: '100%',
    justifyContent: 'center',
  },
  rowC3_text: {
    fontSize: 20,
    color: '#026670',
  },
  rowC4_view: {
    padding: 4,
    backgroundColor: '#fff',
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    width: '30%',
    height: '100%',
    justifyContent: 'center',
    paddingLeft: 10,
  },
  rowC4_text: {
    fontSize: 14,
    color: '#026670',
  },
  rowC5_view: {
    padding: 4,
    backgroundColor: '#fff',
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    width: '12.5%',
    height: '100%',
    justifyContent: 'center',
  },
  rowC6_view: {
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    backgroundColor: '#FEF9C7',
    paddingLeft: 10,
    paddingBottom: 2,
    width: '22.5%',
    height: '100%',
    justifyContent: 'center',
  },
  rowC6_text: {
    fontSize: 20,
    color: '#026670',
  },
  rowC7_view: {
    paddingBottom: 2,
    backgroundColor: '#fff',
    borderTopWidth: 2,
    borderTopColor: '#FCE181',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    width: '40%',
    height: '100%',
    justifyContent: 'center',
    paddingLeft: 10,
  },
  rowC7_text: {
    fontSize: 12,
    color: '#026670',
  },

  headingMain_view: {
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    paddingLeft: 10,
    paddingBottom: 5,
    paddingTop: 5,
    height: 40,
  },
  headingMain_text: {
    fontSize: 20,
    color: '#026670',
    fontWeight: 'bold',
  },
  fieldTitle_view: {
    backgroundColor: '#FEF9C7',
    paddingLeft: 10,
    height: 25,
    justifyContent: 'center',
    paddingBottom: 2,
  },
  fieldTitle_text: {
    fontSize: 20,
    color: '#026670',
  },
  fieldBody_view: {
    padding: 4,
    backgroundColor: '#fff',
    borderBottomWidth: 2,
    borderBottomColor: '#FCE181',
    height: 80,
  },
  fieldBody_text: {
    fontSize: 14,
    color: '#026670',
  },
};
